language: node_js

node_js:
  - 'stable'

sudo: false

matrix:
  fast_finish: true

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install
  - npm run build

script:
  - node built/local/tsc.js --strict index.d.ts

cache:
  directories:
    - node_modules

git:
  depth: 1
