language: node_js

node_js:
  - 'stable'

sudo: false

matrix:
  fast_finish: true

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install

script:
  - npm run build
  - node built/local/tsc.js index.ts

cache:
  directories:
    - node_modules

git:
  depth: 1
